# Generated by Django 6.0.2 on 2026-04-11 10:42

from django.db import migrations


GROUPS_PERMISSIONS = {
    'Manager': [{
        'content_type': 'car',
        'permissions': [
            'approve_car',
            'remove_car_owner',
            'change_car_owner',
        ]},
        {'content_type': 'repair',
        'permissions': [
            'change_repair_mechanic',
        ]},
        {'content_type': 'invoice',
        'permissions': [
            'add_invoice',
            'delete_invoice',
        ]},
     ],
    'Mechanic': [{
        'content_type': 'repair',
        'permissions': [
            'add_repair',
            'change_repair',
            'change_repair_status',]
    },{
        'content_type': 'part',
        'permissions': [
            'add_part',
            'change_part',
            'delete_part',]
    },]
}






def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group, types_and_permissions in GROUPS_PERMISSIONS.items():
        group_instance, _ = Group.objects.get_or_create(name=group)

        for content_type_permissions in types_and_permissions:
            content_type = content_type_permissions.get('content_type')
            permissions = content_type_permissions.get('permissions')

            for perm in permissions:
                permission = Permission.objects.get(codename=perm, content_type__model=content_type)
                group_instance.permissions.add(permission)




def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=GROUPS_PERMISSIONS.keys()).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cars', '0002_alter_car_options'),
        ('repairs', '0002_alter_repair_options'),
     #   ('invoices' '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
