# Generated by Django 6.0.2 on 2026-04-13 14:31

import cars.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Volvo', 'Volvo'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Volkswagen')], max_length=30)),
                ('model', models.CharField(max_length=40)),
                ('plate', models.CharField(max_length=10, unique=True, validators=[cars.validators.PlateValidator()])),
                ('year', models.PositiveIntegerField(validators=[cars.validators.ProductionYearValidator()])),
                ('engine_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('LPG', 'LPG')], max_length=10)),
                ('mileage', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/images')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
