# Generated by Django 6.0.2 on 2026-02-18 20:27

import cars.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('volvo', 'Volvo'), ('mercedes', 'Mercedes'), ('volkswagen', 'Volkswagen')], max_length=30)),
                ('model', models.CharField(max_length=40)),
                ('plate', models.CharField(max_length=10, unique=True, validators=[cars.validators.PlateValidator()])),
                ('year', models.PositiveIntegerField(validators=[cars.validators.ProductionYearValidator()])),
                ('engine_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG')], max_length=10)),
                ('mileage', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/images')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='profiles.profile')),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
