# Generated by Django 6.0.2 on 2026-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Volvo', 'Volvo'), ('Mercedes', 'Mercedes'), ('Volkswagen', 'Volkswagen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('LPG', 'LPG')], max_length=10),
        ),
    ]
