# Generated by Django 6.0.2 on 2026-04-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', 'model'], 'permissions': [('approve_car', 'Can approve car'), ('remove_car_owner', 'Can remove car owner'), ('change_car_owner', 'Can change car owner')]},
        ),
    ]
